project_id = "wgpjnmdbzdszbldmuqpd"

[functions.export-data]
verify_jwt = false
schedule = "0 0 * * 0"

[functions.get-users]
verify_jwt = false

[functions.api-teams]
verify_jwt = false

[functions.api-players]
verify_jwt = false

[functions.api-matches]
verify_jwt = false

[functions.api-goals]
verify_jwt = false

[functions.api-match-players]
verify_jwt = false

[functions.api-user-roles]
verify_jwt = false
